version: "3.7"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: me
      POSTGRES_DB: news
    volumes:
      - ./pg:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    image: news-article-api/v1.0
    depends_on:
      - db
    ports:
      - "4000:4000"
  ui:
    image: news-article-react-fe/v1.0
    depends_on:
      - web
    ports:
      - "3000:3000"
