version: "3.7"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: me
      POSTGRES_DB: movie
    volumes:
      - ./pg:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    image: movie-rest-api/v1.1
    depends_on:
      - db
    ports:
      - "4000:4000"
  ui:
    image: movie-fe/v1.1
    depends_on:
      - web
    ports:
      - "3000:3000"
